### ISSUE TITLE
WebApiContrib.Formatting.Xlsx DLL is not on NuGet

### ISSUE THREAD

**Issue by egucciar** [WebApiContrib/WebApiContrib.Formatting.Xlsx#29]
I'd love to use this library but the DLL it requires isn't on NuGet. I found the DLL on another Github repo, but the DLL should be available as a nuget package. Also EPPlus should have a dependency on this DLL.

**Comment by ChrisMissal** [comment]
I can work on this tonight @jordangray. What's the starting version? 2.0.0?

**Comment by ChrisMissal** [comment]
So I pushed out a version that was a pre-release (1.0.0-pre), but it looked like it failed. The followup was missing the "pre" so it appears listed as 1.0.0. Let me know what you want for this and I can adjust @jordangray :

http://www.nuget.org/packages/WebApiContrib.Formatting.Xlsx

**Comment by jordangray** [comment]
Many thanks, Chris! Things are a bit intense right now, just want to acknowledge that the version is fine for now, and I'll update the documentation when I get a chance. :)

**Comment by ChrisMissal** [comment]
I completely understand, thanks!
