### ISSUE TITLE
Allow generated Excel filename to be specified

### ISSUE THREAD

**Issue by jordangray** [WebApiContrib/WebApiContrib.Formatting.Xlsx#3]
Should probably add this as a new attribute that can be added to the class.

**Comment by imperugo** [comment]
What if I want to calculate the file name?
For example specifying the current date "dd-MM-yyyy.xslx" ?

I tried to put my `ContentDisposition` name but it seems you formatter overrides my value.
What about to write the `ContentDisposition` header only if there isn't another one?

**Comment by jordangray** [comment]
Someone has actually made [a fork that adds the current date to the file name](https://github.com/brettmas/WebApiContrib.Formatting.Xlsx). :)

But this does seem like a reasonable thing to want. For now, overriding `ContentDisposition` seems like this best solution, but feel free to open a feature request for generated file names.
