### ISSUE TITLE
Sample won't run

### ISSUE THREAD

**Issue by D-Bullock** [WebApiContrib/WebApiContrib.Formatting.Xlsx#37]
The sample (as downloaded from github) doesn't run. 
"The type or namespace name 'Ajax' does not exist in the namespace 'System.Web.Mvc'"

**Comment by jordangray** [comment]
Thanks for reporting that, I'll take a look. May I ask what IDE and .NET runtime you're using?

**Comment by D-Bullock** [comment]
I'm running Visual Studio (both 2013 and the 2015 pre-release), though unsure how to check which .Net runtime. I believe I have everything up to 4.6 installed.

**Comment by jordangray** [comment]
So I tried running the sample project on a fresh machine, and it runs first time. I've checked that it's set to copy the assembly locally too.

I'm attending to some personal business until the end of this month, but come April I'll have another look at this. In the meantime, if you happen to think of anything that might be relevant, throw it this way and I'll be very appreciative! :)

**Comment by jordangray** [comment]
I've had trouble reproducing this, so I'm closing this issue for now, but thank you for reporting it—and feel free to comment and reopen it if you have any more information! :)

Also, if you (or anyone with a similar issue) has a spare moment, I'd be really grateful if you could [try some of these suggestions from StackOverflow](http://stackoverflow.com/questions/11071392/the-type-or-namespace-name-does-not-exist-in-the-namespace-system-web-mvc) and comment on whether any of them work?
