### ISSUE TITLE
HeaderHeight default of 0

### ISSUE THREAD

**Issue by ChrisMissal** [WebApiContrib/WebApiContrib.Formatting.Xlsx#38]
I noticed the default value for `headerHeight` is 0. Is this intentional?

https://github.com/WebApiContrib/WebApiContrib.Formatting.Xlsx/blob/ef0e3024ceb13d029e53caa7fe1a7242d44a2764/src/WebApiContrib.Formatting.Xlsx/XlsxMediaTypeFormatter.cs#L69

In Google Spreadsheets, this doesn't seem to be an issue, but in Excel, this makes the first row/header effectively "hidden". Can I change this to be a nullable double and if omitted, use the default row height instead?

**Comment by ChrisMissal** [comment]
@jordangray I attached a pull request. Let me know if you have questions about this.

**Comment by jordangray** [comment]
@ChrisMissal You're right, `headerHeight` should be null instead of 0. I must have forgotten to update the parameter type when I made the property nullable. Thanks for spotting! I'll check and merge when I get home.

**Comment by ChrisMissal** [comment]
@jordangray bump :)

**Comment by jordangray** [comment]
@ChrisMissal Thanks for bumping! Just merged your pull request.
