### ISSUE TITLE
JsonFormatter and XlsxMediaTypeFormatter don't play nice with each other

### ISSUE THREAD

**Issue by yangmail2002** [WebApiContrib/WebApiContrib.Formatting.Xlsx#42]
When use JsonFormatter  And XlsxMediaTypeFormatter together，it'll not work correctly.

**Comment by jordangray** [comment]
Hey @yangmail2002! Could you provide a few more details on what's going wrong? Some more details on what sort of exceptions/build issues you're seeing and some example code so that I can get a repro would be really helpful!

**Comment by jordangray** [comment]
Hi again @yangmail2002—just wondering if you have any more information about this issue? I'll leave this issue open another couple of days; if you don't get back, I'll see if I have problems using `JsonFormatter` with the sample project and close it if I can't find any.

**Comment by jordangray** [comment]
Cannot reproduce, closing issue. Feel free to reopen if you have any further details, though! :)
