### ISSUE TITLE
Make formatter work with data in a DataTable

### ISSUE THREAD

**Issue by yido** [WebApiContrib/WebApiContrib.Formatting.Xlsx#44]
I have tried to generate the model dynamicaly but it doesnt seem working.

**Comment by jordangray** [comment]
Hi @yido!

So, if I understand correctly, the columns returned by your query are indeterminate, presumably because they could come from arbitrary queries—is that right?

Also, when you say "datatable," do you mean an instance of the [`DataTable`](https://msdn.microsoft.com/en-us/library/system.data.datatable%28v=vs.110%29.aspx) class?

**Comment by jordangray** [comment]
Suggested resolution: right now, there are only the built-in ways of resolving properties and values to be serialised. It might be better if, in a future version, it was possible to provide a customisable mechanism for adding property resolvers that can return a list of properties (columns) or get (cell) values depending on the type of object being passed.

This way, there could be resolvers for dictionaries, dynamics, expando opbjects… and, yes, `DataTable`s. I'll think on it over the weekend; this might help with another issue raised by someone else.

**Comment by jordangray** [comment]
@yido: the resolution to #43 (added in #47) should make it possible for you to write your own column resolver for `DataTable`. You'll be able to get this soon on NuGet as `2.0.0-pre`, or you can grab it now in the `pre` branch.

I'm still working on the documentation for this feature. Would you like a sneak peek and some guidance on how to get this working?

_(Closing issue, but feel free to continue commenting. Alternatively, email me—__j.b.gray at gmail__.)_

**Comment by yido** [comment]
ok thanks so much jordangray!
Thanks for help
