### ISSUE TITLE
Expando object export to excel

### ISSUE THREAD

**Issue by balajichekka** [WebApiContrib/WebApiContrib.Formatting.Xlsx#46]
Please expand this excellent framework to add support for exporting dyanmic objects (Expando objects).

**Comment by jordangray** [comment]
Thanks for letting me know you're interested—working on this in #45, follow that issue for updates! :)

**Comment by jordangray** [comment]
PS: the related issue has been updated, feel free to check it out if you want to give some early feedback!

**Comment by balajichekka** [comment]
Hi, i tested it, working great with my list of dynamic objects.
thanks,
when are you going to publish.

**Comment by jordangray** [comment]
Great—glad to hear it's working for you, and thanks for the early feedback! I've got a few kinks and niggles to work out; for now with a related issue, so I'll maybe push it to a dev branch with a view to getting it ready for the current release next weekend.

I'll let you know if there are any big changes between now and then that you need to know about, but I'm reasonably confident that the `ExpandoObject` support at least will remain mostly unchanged.
